spring:
  profiles:
    active: dev
  application:
    name: hirescope-backend
  main:
    web-application-type: servlet

  jackson:
    default-property-inclusion: non_null  # null 필드 JSON 응답에서 자동 제외

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: redis

server:
  port: 8080

ai-server:
  url: http://localhost:8000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.project.hirescopebackend: DEBUG
    org.hibernate.SQL: DEBUG
