spring:
  profiles:
    active: dev
  application:
    name: hirescope-backend
  main:
    web-application-type: servlet  # webflux 공존 시 MVC 모드 강제 지정
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: redis

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
